import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

interface PatternSeed {
  name: string;
  category: string;
  riskScore: number;
  description: string;
  whyItWorks: string;
  howToSpot: string;
  icon: string;
  ageExplanation10: string;
  ageExplanation14: string;
  detectionSignals: string[];
  examples: string[];
}

const patterns: PatternSeed[] = [
  // CATEGORY 1: ATTENTION CAPTURE
  {
    name: 'Punch-In Zoom',
    category: 'Attention Capture',
    riskScore: 3,
    description: 'Editor cuts from a wide shot to a sudden close-up on the speaker\'s face, often mid-sentence, to refresh visual interest without changing scene.',
    whyItWorks: 'Exploits the orienting reflex — the brain involuntarily attends to sudden changes in visual scale, releasing a small attention "reset" that prevents drop-off.',
    howToSpot: 'Look for the camera suddenly jumping closer without the scene actually changing.',
    icon: 'fa-search-plus',
    ageExplanation10: 'The camera suddenly jumps closer to wake your eyes up so you don\'t get bored.',
    ageExplanation14: 'A punch-in zoom is a soft attention reset — the editor knows your brain will involuntarily re-engage when scale or framing changes, so they use it instead of a real new idea.',
    detectionSignals: ['Identical background, lighting, and audio continuity', 'Framing tightens >25% in a single frame transition'],
    examples: ['MrBeast challenges', 'Penguinz0 commentary', 'Gaming reactions'],
  },
  {
    name: 'Text-Overlay Anchor',
    category: 'Attention Capture',
    riskScore: 3,
    description: 'Bold, large-font text overlaid on the screen summarizing the current beat ("3 RULES," "WATCH THIS MISTAKE").',
    whyItWorks: 'Reduces cognitive load and serves as a verbal-visual "anchor" so viewers don\'t drift; the human visual system processes images vastly faster than text reading aloud.',
    howToSpot: 'Notice big words popping up on screen every few seconds — they\'re keeping your eyes locked in.',
    icon: 'fa-font',
    ageExplanation10: 'Big words pop up on screen so you don\'t get confused and look away.',
    ageExplanation14: 'On-screen text creates a redundant channel — your eyes can re-anchor at any moment without rewinding, lowering the cost of staying.',
    detectionSignals: ['Text appearing every 5–15 seconds', 'Sans-serif, high-contrast, often white-on-black-stroke fonts'],
    examples: ['Educational/finance TikToks', 'MrBeast challenges with "$10,000 PRIZE" overlays', 'Recipe Reels'],
  },
  {
    name: 'Hyper-Cut Pacing',
    category: 'Attention Capture',
    riskScore: 5,
    description: 'Continuous jump cuts removing every pause, breath, or filler, producing one new visual event every 1–3 seconds. Also called "retention editing."',
    whyItWorks: 'Each cut produces a micro-orienting response; the brain\'s habituation circuits can\'t downregulate fast enough.',
    howToSpot: 'Count how many times the image changes in 5 seconds. More than 4? That\'s hyper-cut pacing!',
    icon: 'fa-bolt',
    ageExplanation10: 'If a video never lets you take a breath, it\'s because they don\'t want your brain to even think about leaving.',
    ageExplanation14: 'Sub-3-second cut frequency is the most reliable visual signal that a video is engineered to defeat YouTube\'s drop-off curve.',
    detectionSignals: ['Median shot length under 3 seconds', 'Absence of any continuous take longer than 6 seconds in the first minute'],
    examples: ['MrBeast videos', 'Almost all TikToks', 'YouTube Shorts'],
  },
  {
    name: 'Pattern Interrupt',
    category: 'Attention Capture',
    riskScore: 5,
    description: 'A sudden sound effect, meme insert, freeze-frame, or color shift dropped in approximately every 25–40 seconds to re-capture drifting attention.',
    whyItWorks: 'Habituation theory — a steady stimulus loses salience; a violation of the established pattern restores attention. Editors describe this as a "mini wake-up."',
    howToSpot: 'Notice random ding noises or meme pictures that appear out of nowhere — they\'re grabbing you back.',
    icon: 'fa-random',
    ageExplanation10: 'Random ding noises or meme pictures appear to grab you back when your mind starts wandering.',
    ageExplanation14: 'Pattern interrupts exploit the brain\'s novelty-detection system; their placement is timed to the standard 30-second viewer drop-off curve.',
    detectionSignals: ['Non-diegetic sound stings (boings, vines, air horns)', '1-frame meme/image inserts', 'Sudden desaturate-to-red color shift'],
    examples: ['Penguinz0', 'Gaming commentary', 'Reaction YouTube'],
  },
  {
    name: 'Exaggerated-Face Thumbnail',
    category: 'Attention Capture',
    riskScore: 6,
    description: 'Thumbnail features a human face with open mouth, wide eyes, or shocked expression, frequently photoshopped beyond what occurs in the video.',
    whyItWorks: 'The fusiform face area of the human visual cortex has dedicated face-detection circuitry that prioritizes emotional faces over neutral images. Expressive-face thumbnails raise CTR by 20–30%.',
    howToSpot: 'Ask yourself: "Would a real person actually react this way?" The shocked face is usually fake.',
    icon: 'fa-theater-masks',
    ageExplanation10: 'The shocked face on the thumbnail is fake — they made that face on purpose to make you click.',
    ageExplanation14: 'Thumbnails with exaggerated faces exploit the fusiform face area\'s bias toward high-arousal expressions; the pictured face rarely appears in the video itself.',
    detectionSignals: ['Open mouth + wide eyes + isolated face filling >25% of thumbnail', 'Red/yellow saturated background', 'Arrows or circles drawn on the image'],
    examples: ['MrBeast', 'Almost all major YouTube channels', 'Prank channels', 'Reaction videos'],
  },
  {
    name: 'Sensory Saturation',
    category: 'Attention Capture',
    riskScore: 8,
    description: 'Continuous bright, high-contrast colors + wall-to-wall musical bed + scene changes every 1–2 seconds aimed at very young children.',
    whyItWorks: 'The brain gets a hit of dopamine from screen-time and the stronger the stimulation a show delivers, the stronger the "hit." Children develop tolerance, then distress when removed.',
    howToSpot: 'If a video is super bright, super fast, and never has a quiet moment — it\'s designed like sugar for the brain.',
    icon: 'fa-sun',
    ageExplanation10: 'Some little-kid shows are made to be like sugar for the brain — too bright, too fast, and hard to stop watching.',
    ageExplanation14: 'Sensory-saturation content induces a stimulant-like dopamine response; toddlers shown for hours develop dysregulation similar to withdrawal when the screen is removed.',
    detectionSignals: ['Scene change every <2 seconds', 'Saturation/brightness consistently near 100%', 'Continuous wall-to-wall music with no silences'],
    examples: ['CoComelon', 'AI-generated YouTube Kids "nursery rhyme" channels'],
  },
  {
    name: 'Misleading Thumbnail',
    category: 'Attention Capture',
    riskScore: 9,
    description: 'Thumbnail depicts an event or image that does not occur in the video (explosion, celebrity, surgery image), often AI-generated.',
    whyItWorks: 'Exploits the curiosity gap — the discomfort produced by the difference between what one knows and what one wants to know.',
    howToSpot: 'If the cool thing on the picture never happens in the video, the video lied to make you click.',
    icon: 'fa-image',
    ageExplanation10: 'If the cool thing on the picture never happens in the video, the video lied to make you click.',
    ageExplanation14: 'Misleading thumbnails are the most-cited form of YouTube clickbait; the algorithm penalizes them only if click-through rate is high but watch time is low.',
    detectionSignals: ['Element in thumbnail never appears in the first 60s of the video', 'Suspiciously perfect lighting consistent with AI generation', 'Mismatch between thumbnail emotion and actual content'],
    examples: ['AI-generated news channels', 'Celebrity-gossip YouTube', '"You won\'t believe" prank channels'],
  },
  // CATEGORY 2: EMOTIONAL MANIPULATION
  {
    name: 'Wholesome Bait',
    category: 'Emotional Manipulation',
    riskScore: 4,
    description: 'Manufactured "feel-good" content — staged kindness, scripted "helping the homeless" videos — designed to trigger sharing and parasocial loyalty.',
    whyItWorks: 'Activates oxytocin and the brain\'s prosocial reward system; "moral elevation" content is among the most-shared categories online.',
    howToSpot: 'Ask: "How did they get the camera in the perfect spot for this \'random\' act of kindness?"',
    icon: 'fa-heart',
    ageExplanation10: 'Some videos that look super kind are actually filmed on purpose to make people share them.',
    ageExplanation14: 'Wholesome bait monetizes moral elevation; the asymmetry between the brief act of kindness and the millions in ad revenue is the tell.',
    detectionSignals: ['Multiple camera angles on a "spontaneous" act', 'Subject\'s reaction visible from impossible camera position', 'Channel posts only "kindness" videos'],
    examples: ['Giveaway / "giving back" YouTube channels', 'Instagram Reels of acts of kindness'],
  },
  {
    name: 'Tear-Jerker Setup',
    category: 'Emotional Manipulation',
    riskScore: 5,
    description: 'Slow, sad piano + slow zoom + personal-tragedy narration deployed to create emotional investment before an ask (subscribe, buy, donate).',
    whyItWorks: 'Sad music + visual slowness shifts the viewer into a parasympathetic, suggestible state; emotion drives memory consolidation, increasing brand recall.',
    howToSpot: 'Sad piano + slow zoom-in usually means they want you to feel something so you\'ll do what they ask next.',
    icon: 'fa-sad-tear',
    ageExplanation10: 'Sad piano + slow zoom-in usually means they want you to feel something so you\'ll do what they ask next.',
    ageExplanation14: 'Affective priming with slow music puts viewers into a low-arousal, high-empathy state where persuasion thresholds drop.',
    detectionSignals: ['Piano-only soundtrack <80 BPM', 'Slow zoom of >3 seconds', 'Voice-over volume dipped below music level at climax'],
    examples: ['Donation-appeal channels', '"Story-time" TikToks', 'Influencer apology videos'],
  },
  {
    name: 'Fear Hook',
    category: 'Emotional Manipulation',
    riskScore: 6,
    description: 'Opening line/image triggers threat or anxiety ("This common food is silently killing you," "9 out of 10 parents miss this danger").',
    whyItWorks: 'Negativity bias — the amygdala prioritizes threat information. Each additional negative word in a headline raises click-through rate by 2.3%.',
    howToSpot: 'If a video starts by scaring you, the person usually wants to sell you something to fix the scare.',
    icon: 'fa-exclamation-triangle',
    ageExplanation10: 'If a video starts by scaring you, the person usually wants to sell you something to fix the scare.',
    ageExplanation14: 'Each additional negative word in a headline raised click-through rate by 2.3% across 370 million impressions. Algorithmically-driven content therefore drifts toward fear, because fear converts.',
    detectionSignals: ['First 5s contain words like "silently," "killing," "destroying," "you don\'t know"', 'Ominous low-frequency drone', 'Red color flash'],
    examples: ['Health/wellness YouTube', 'Finance TikTok', 'Parenting Reels'],
  },
  {
    name: 'Cringe Bait',
    category: 'Emotional Manipulation',
    riskScore: 7,
    description: 'Content designed to make viewers feel secondhand embarrassment, often by a creator deliberately doing something awkward.',
    whyItWorks: 'Cringe activates both empathy and social-comparison circuitry; viewers stay to confirm their disapproval, generating long watch sessions.',
    howToSpot: 'If a video makes you uncomfortable but you can\'t look away — that discomfort IS the trick.',
    icon: 'fa-grimace',
    ageExplanation10: 'Some videos are *meant* to be uncomfortable to watch — that\'s the whole trick.',
    ageExplanation14: 'Cringe bait converts secondhand embarrassment into watch time; the algorithm cannot distinguish discomfort from interest.',
    detectionSignals: ['Comment section dominated by negative reactions', 'Creator breaks social conventions deliberately'],
    examples: ['TikTok "did this on purpose" creators', 'Reaction content stitching cringe', 'Mukbang'],
  },
  {
    name: 'Rage Bait',
    category: 'Emotional Manipulation',
    riskScore: 9,
    description: 'Online content deliberately designed to elicit anger or outrage by being frustrating, provocative, or offensive, typically posted to increase engagement.',
    whyItWorks: 'Each moral-emotional word raises message diffusion by ~20%; outrage-driven comments are treated as "high-quality engagement" by algorithms.',
    howToSpot: 'If a video makes you angry and you want to comment — that anger IS the product. They profit from your outrage.',
    icon: 'fa-fire-alt',
    ageExplanation10: 'Some people make videos *on purpose* to make people angry, because angry comments mean more money for them.',
    ageExplanation14: 'Rage bait monetizes moral outrage; the angrier the comments thread, the more the algorithm promotes the content, which is why the rage-engagement loop self-reinforces.',
    detectionSignals: ['Confident on-camera assertion of an extreme/offensive position', 'Comment count vastly outpacing like count', 'Deliberate absence of nuance'],
    examples: ['Political commentary channels', 'PlainRock smashing Nintendo Switches', '"I made Goldfish from scratch" controversy creators'],
  },
  // CATEGORY 3: SOCIAL PRESSURE
  {
    name: 'Comment-Bait Question',
    category: 'Social Pressure',
    riskScore: 3,
    description: 'Direct question to the viewer at the end of a video ("What do you think? Drop it in the comments").',
    whyItWorks: 'YouTube\'s algorithm treats comments as a quality signal; the simplest way to elicit them is to ask.',
    howToSpot: 'They ask a question to get you to comment because comments help the video get shown to more people.',
    icon: 'fa-comment-dots',
    ageExplanation10: 'They ask a question to get you to comment because comments help the video get shown to more people.',
    ageExplanation14: 'Comment baiting converts viewer questions into algorithmic distribution; an emotionally polarizing prompt outperforms a neutral one.',
    detectionSignals: ['Direct question in last 30s', 'On-screen text "comment below"'],
    examples: ['Almost every long-form YouTube creator'],
  },
  {
    name: 'In-Group Slang Lexicon',
    category: 'Social Pressure',
    riskScore: 4,
    description: 'Creator- or generation-specific slang ("rizz," "gyatt," "fanum tax," "Skibidi," "sigma") that signals tribal belonging.',
    whyItWorks: 'Vocabulary functions as social currency; children watch unfamiliar slang in part because it determines schoolyard belonging.',
    howToSpot: 'If a video uses weird words to make you feel like you\'re in a special club — that\'s the trick.',
    icon: 'fa-users',
    ageExplanation10: 'Some videos use weird words to make you feel like you\'re in a special club.',
    ageExplanation14: 'In-group lexicon creates "silosociality" (TikTok subcommunities) — knowing the slang is the social proof of belonging, which the algorithm reinforces.',
    detectionSignals: ['Repeated platform-specific neologisms in first 30s', 'On-screen text references inside jokes'],
    examples: ['Skibidi Toilet derivatives', 'Gen Alpha TikTok', 'Gaming streamers'],
  },
  {
    name: 'Like-and-Subscribe Demand',
    category: 'Social Pressure',
    riskScore: 5,
    description: 'Direct verbal request to subscribe, frequently with mild guilt or reward framing ("Only 30% of you are subscribed").',
    whyItWorks: 'Combines reciprocity — "I gave you a free video, you give me a sub" — with social-proof framing.',
    howToSpot: 'Asking you to subscribe is asking for a favor. You don\'t have to do it.',
    icon: 'fa-bell',
    ageExplanation10: 'Asking you to subscribe is asking for a favor. You don\'t have to do it.',
    ageExplanation14: 'CTA framing exploits implicit reciprocity; data tells creators that CTAs lift subscription rates measurably even when viewers report finding them annoying.',
    detectionSignals: ['"Subscribe" arrow animation', 'Statement of percent of audience that isn\'t subscribed'],
    examples: ['Universal across YouTube'],
  },
  {
    name: 'Social Proof Inflation',
    category: 'Social Pressure',
    riskScore: 6,
    description: 'Display or verbal mention of huge view counts, subscriber counts, or "everyone is watching this" framing.',
    whyItWorks: 'Cialdini\'s social-proof principle: people preferentially engage with what others engage with. View count + subscriber badge function as on-screen social proof.',
    howToSpot: 'Lots of views doesn\'t mean the video is good — it just means lots of other people clicked.',
    icon: 'fa-chart-line',
    ageExplanation10: 'Lots of views doesn\'t mean the video is good — it just means lots of other people clicked.',
    ageExplanation14: 'Social proof shortcuts evaluation: "if 10M people watched, it must be worth my time." This conformity heuristic was originally evolutionarily protective; in an algorithmic context it amplifies whatever the algorithm already favored.',
    detectionSignals: ['View count overlaid as graphic', '"1M views in 24 hrs" callouts', '"Most watched" framing'],
    examples: ['YouTube trending pages', '"As seen on" tags', 'Influencer follower counts'],
  },
  {
    name: 'Parasocial Intimacy',
    category: 'Social Pressure',
    riskScore: 7,
    description: 'Direct-address camera, "you guys," "fam," personal-life disclosure, fourth-wall breaks — all of which produce a one-sided sense of friendship.',
    whyItWorks: 'Children 8–12 form parasocial relationships strong enough to override advertising-literacy defenses when a sponsorship is disclosed.',
    howToSpot: 'When a YouTuber calls you "best friend," remember they don\'t actually know you — but your brain might feel like they do.',
    icon: 'fa-user-friends',
    ageExplanation10: 'When a YouTuber calls you "best friend," remember they don\'t actually know you — but your brain might feel like they do.',
    ageExplanation14: 'Parasocial cues suppress critical thinking; research shows children with strong parasocial bonds rate disclosed sponsorships *more positively* than non-disclosed ones.',
    detectionSignals: ['Continuous direct-to-camera eye contact', 'Use of "you guys / fam / besties"', 'Personal disclosure unprompted', 'Reference to the viewer as if known'],
    examples: ['Most lifestyle/vlog YouTubers', 'Gaming streamers', 'GRWM TikToks'],
  },
  {
    name: 'Pile-On / Stitch Calling-Out',
    category: 'Social Pressure',
    riskScore: 7,
    description: 'Creator stitches or duets another user to publicly critique them, inviting audience to join the pile-on.',
    whyItWorks: 'Combines tribal in-group reinforcement with moral outrage; targets feel the cost, the creator harvests engagement.',
    howToSpot: 'If a video is getting everyone to be mean to one person — that\'s still bullying, even if it\'s online.',
    icon: 'fa-bullhorn',
    ageExplanation10: 'Sometimes a person makes a video to get everyone to be mean to one other person. That\'s still bullying.',
    ageExplanation14: 'Stitch-callouts weaponize parasocial loyalty; the creator\'s followers act as a coordinated harassment swarm in exchange for in-group belonging.',
    detectionSignals: ['Split-screen with another user', 'Sneering or mocking tone', 'Comment section piling on a named individual'],
    examples: ['TikTok callout culture', '"This guy" Reels'],
  },
  {
    name: 'Public Loyalty Display',
    category: 'Social Pressure',
    riskScore: 7,
    description: 'Twitch sub badges, channel-points emotes, "OG fan" signifiers, super-chat highlights that publicly reward loyalty and spending.',
    whyItWorks: 'Status hierarchies + loss aversion (losing the badge is more painful than gaining the equivalent value).',
    howToSpot: 'Special badges for fans who pay are a way to make people feel left out if they don\'t spend money.',
    icon: 'fa-award',
    ageExplanation10: 'Some streamers give special badges only to fans who pay — that\'s a way to make people feel left out if they don\'t.',
    ageExplanation14: 'Loyalty badges convert money into visible identity; the threat of losing status (loss aversion) is what sustains the recurring subscription.',
    detectionSignals: ['Public sub leaderboard', '"Longest sub" callouts', 'Badge tiers based on months subscribed'],
    examples: ['Twitch subscriber-only emotes', 'YouTube channel memberships', 'Patreon tiers'],
  },
  // CATEGORY 4: TEMPORAL MANIPULATION
  {
    name: 'Speed Ramping',
    category: 'Temporal Manipulation',
    riskScore: 3,
    description: 'Footage sped up 2–8× to compress waiting/repetitive sequences.',
    whyItWorks: 'Removes dead time; the manipulative variant compresses real-time challenges to make stakes feel higher than they were.',
    howToSpot: 'They make boring parts go fast so you don\'t get bored — mostly harmless, but watch for fake stakes.',
    icon: 'fa-forward',
    ageExplanation10: 'They make boring parts go fast so you don\'t get bored.',
    ageExplanation14: 'Speed ramping is mostly ethical pacing; the manipulative variant compresses real-time challenges to make stakes feel higher than they were.',
    detectionSignals: ['Pitch-shifted audio', 'Clock-on-wall visibly skipping'],
    examples: ['Cooking videos', 'Time-lapse construction', 'Gameplay montages'],
  },
  {
    name: 'Cliffhanger Sequencing',
    category: 'Temporal Manipulation',
    riskScore: 5,
    description: 'Each video ends mid-arc; the resolution requires watching the next video. Multi-part series ("Day 1 of 100").',
    whyItWorks: 'Zeigarnik effect — unfinished tasks remain active in working memory. The brain\'s left caudate (linked to dopamine reward pathway) responds strongly when information gaps emerge.',
    howToSpot: 'Your brain hates not knowing the ending — so they cut it off on purpose to make you come back.',
    icon: 'fa-mountain',
    ageExplanation10: 'Your brain hates not knowing the ending — so they cut it off on purpose to make you come back.',
    ageExplanation14: 'Cliffhangers exploit the Zeigarnik effect; the same cognitive incompleteness that drives productive learning is weaponized to keep you in-app.',
    detectionSignals: ['"Part 1/2/3" titles', 'Video ends mid-sentence', '"Continue in the next video"'],
    examples: ['"I survived 100 days in Minecraft" series', 'Story-time TikTok parts 1/2/3', 'Vlogger story arcs'],
  },
  {
    name: 'Countdown Timer',
    category: 'Temporal Manipulation',
    riskScore: 6,
    description: 'Visible on-screen countdown ("only 2 minutes left," "47 seconds to decide") used inside content or in live streams.',
    whyItWorks: 'Countdown creates time-pressure that bypasses deliberative evaluation. Cortisol rises; decisional thresholds drop.',
    howToSpot: 'When you see a timer counting down, your brain panics a little — that\'s the trick. Pause and ask: "What happens if I just wait?"',
    icon: 'fa-hourglass-half',
    ageExplanation10: 'When you see a timer counting down, your brain panics a little — that\'s the trick.',
    ageExplanation14: 'Visible countdowns trigger a stress response that narrows attention to the offer and away from comparison or reflection.',
    detectionSignals: ['On-screen clock', 'Pulsing red border', 'Voice-over urgency phrases ("running out")'],
    examples: ['Live shopping streams (TikTok Shop, Whatnot)', 'Flash-sale Reels', 'Quiz/trivia YouTube'],
  },
  {
    name: 'Fake Urgency',
    category: 'Temporal Manipulation',
    riskScore: 7,
    description: 'Claimed limited-time conditions that are not actually limited ("Only today!" repeated daily; "last chance" repeated weekly).',
    whyItWorks: 'Scarcity + urgency exploit loss aversion; the creator can run the same "limited" campaign quarterly because the trick works each time on a fresh emotional baseline.',
    howToSpot: 'When the same person says "today only" every week, it\'s a lie. It\'s never actually only today.',
    icon: 'fa-clock',
    ageExplanation10: 'When the same person says "today only" every week, it\'s a lie. It\'s never actually only today.',
    ageExplanation14: 'Manufactured scarcity exploits loss aversion; the creator can run the same "limited" campaign quarterly because the trick works each time on a fresh emotional baseline.',
    detectionSignals: ['Same urgency language across multiple posts', '"Limited" runs lasting weeks', 'Countdown that resets'],
    examples: ['"Drop just opened" merch videos', '"Secret link in bio for 24 hours"', 'Recurring "final sale"'],
  },
  {
    name: 'Live-Only Exclusivity',
    category: 'Temporal Manipulation',
    riskScore: 7,
    description: 'Promising that something will only happen during the live stream and not be available afterward, to pressure synchronous viewing.',
    whyItWorks: 'Pure FOMO — the viewer rearranges schedule to avoid missing out; creator gets concentrated concurrent-viewer numbers that boost algorithmic visibility.',
    howToSpot: 'If a streamer says it\'ll only happen live, that\'s pressure to drop everything and watch right now.',
    icon: 'fa-broadcast-tower',
    ageExplanation10: 'If a streamer says it\'ll only happen live, that\'s pressure to drop everything and watch right now.',
    ageExplanation14: 'Live-only framing converts time-flexibility into a scarce good; the urgency drives concurrent metrics that platforms reward.',
    detectionSignals: ['"Live only"', '"Won\'t be on the VOD"', 'Countdown to start', 'Pre-roll teasers'],
    examples: ['Influencer Q&A streams', 'Gaming "reveal" streams', 'Twitch milestones'],
  },
  // CATEGORY 5: REWARD LOOPS
  {
    name: 'Oddly Satisfying / ASMR Closure',
    category: 'Reward Loops',
    riskScore: 4,
    description: 'Short loops of cleaning, organizing, slime, or symmetrical processes that produce a sense of completion.',
    whyItWorks: 'Closure produces dopamine in the seeking system; ASMR triggers tingling and parasympathetic activation, engaging social-bonding circuits.',
    howToSpot: 'Some videos give you a relaxed feeling — that\'s real, but it can also make it hard to stop watching.',
    icon: 'fa-spa',
    ageExplanation10: 'Some videos give you a relaxed feeling — that\'s real, but it can also make it hard to stop watching.',
    ageExplanation14: 'ASMR/satisfying content delivers a benign micro-reward, but the same dopamine pathway underlies habituation and tolerance.',
    detectionSignals: ['Whispered audio', 'Close-up tactile manipulation', 'Symmetrical/repetitive process', 'Total-duration playlists'],
    examples: ['"Oddly Satisfying" channels', 'Cleaning TikToks (CleanTok)', 'Slime compilations'],
  },
  {
    name: 'Streak / Progression Cues',
    category: 'Reward Loops',
    riskScore: 6,
    description: 'Day-N counts ("Day 47 of working out"), challenge series, season-pass tiers — explicit progression markers.',
    whyItWorks: 'Endowed-progress effect (people work harder to complete a task when they feel they\'ve already started); breaking the streak feels like loss.',
    howToSpot: 'Counting up makes your brain want to keep counting. That\'s a trick.',
    icon: 'fa-fire',
    ageExplanation10: 'Counting up makes your brain want to keep counting. That\'s a trick.',
    ageExplanation14: 'Streaks weaponize endowed progress and loss aversion — discontinuing the watch breaks an accumulated "investment" the user feels they own.',
    detectionSignals: ['Day-counter overlay', '"Don\'t break the streak" CTAs', 'Visible streak meter'],
    examples: ['Fitness creators', '"100 days of X" YouTube series', 'Twitch sub-streaks'],
  },
  {
    name: 'Unboxing / Reveal Loop',
    category: 'Reward Loops',
    riskScore: 6,
    description: 'Video structured as a sequence of small reveals (box → wrapping → item; mystery box; "what\'s in the bag").',
    whyItWorks: 'Each reveal is a small variable reward, matching the slot-machine intermittent-reinforcement schedule.',
    howToSpot: 'Unboxing videos give your brain little surprises over and over — like a treasure game that doesn\'t really end.',
    icon: 'fa-box-open',
    ageExplanation10: 'Unboxing videos give your brain little surprises over and over — like a treasure game that doesn\'t really end.',
    ageExplanation14: 'Sequential reveals approximate a variable-reward schedule; each layer delays gratification just enough to keep the dopamine system primed.',
    detectionSignals: ['Multiple cuts to packaging removal', 'Thumbnails of an unrevealed item', 'Gasps/exclamations at each layer'],
    examples: ['Ryan\'s World', 'Toy review channels', 'Sneaker unboxing', 'Mystery-box channels'],
  },
  {
    name: 'Twitch Channel Points & Gamification',
    category: 'Reward Loops',
    riskScore: 7,
    description: 'Points earned by watching/chatting, redeemable for emotes, song requests, or stream interventions; tiered sub badges; community challenges.',
    whyItWorks: 'Gamification + intrinsic motivation; points convert time-spent into perceived ownership that users won\'t want to abandon.',
    howToSpot: 'Watching to earn points is the same kind of thing as a video game — designed so you don\'t want to stop.',
    icon: 'fa-gamepad',
    ageExplanation10: 'Watching to earn points is the same kind of thing as a video game — designed so you don\'t want to stop.',
    ageExplanation14: 'Channel-points systems are explicitly gamified loyalty programs; they convert idle watch time into an investment users won\'t want to abandon.',
    detectionSignals: ['Points counter on screen', 'Reward menu visible', 'Emote tiers unlocked by sub months'],
    examples: ['Every Twitch partner', 'YouTube channel memberships emulating the pattern'],
  },
  {
    name: 'Like-Counter Slot Machine',
    category: 'Reward Loops',
    riskScore: 8,
    description: 'The visible real-time like/heart counter on Reels, TikTok lives, and live streams, plus animated heart emissions.',
    whyItWorks: 'Variable-ratio reinforcement is the most resistant-to-extinction schedule known in operant conditioning. The visible counter externalizes it, intensifying the dopamine response.',
    howToSpot: 'Watching your likes go up is like a slot machine — your brain treats each ding like a tiny win.',
    icon: 'fa-dice',
    ageExplanation10: 'Watching your likes go up is like a slot machine — your brain treats each ding like a tiny win.',
    ageExplanation14: 'Variable-ratio reinforcement (Skinner) is the most addictive reward schedule; the visible counter externalizes it, intensifying the dopamine response.',
    detectionSignals: ['Real-time animated counter', 'Haptic feedback on like', 'Hearts/coins floating up the screen'],
    examples: ['TikTok live hearts', 'Instagram likes', 'YouTube real-time view counters during premieres'],
  },
  {
    name: 'Variable-Reward Feed',
    category: 'Reward Loops',
    riskScore: 10,
    description: 'Algorithmically personalized infinite feed where each swipe is statistically likely but not certain to deliver a hit of pleasurable content.',
    whyItWorks: 'TikTok\'s algorithm understood bot preferences in less than two hours. Combines the strongest reinforcement schedule known to behavioral psychology with high-fidelity personalization.',
    howToSpot: 'TikTok is like a slot machine you don\'t have to pay for — but the prize is your time.',
    icon: 'fa-infinity',
    ageExplanation10: 'TikTok is like a slot machine you don\'t have to pay for — but the prize is your time.',
    ageExplanation14: 'Algorithmic variable-reward feeds combine the strongest reinforcement schedule known to behavioral psychology with high-fidelity personalization; the WSJ\'s 2021 experiment showed it can lock a user into a content silo in two hours or less.',
    detectionSignals: ['Vertical swipe interface', 'No end-state', 'No chronological order', 'Rapidly narrowing topical focus'],
    examples: ['TikTok For You Page', 'Instagram Reels', 'YouTube Shorts'],
  },
  // CATEGORY 6: COGNITIVE OVERLOAD
  {
    name: 'Multi-Frame Stimulation',
    category: 'Cognitive Overload',
    riskScore: 7,
    description: 'Two unrelated videos stacked vertically — a TikTok creator on top, Subway Surfers / Minecraft parkour underneath — to occupy any drifting attention.',
    whyItWorks: 'Splits attention so that neither stream is fully processed but both prevent disengagement; defeats the brain\'s ability to decide to leave.',
    howToSpot: 'When two videos play at once, your brain can\'t think clearly about either one — that\'s the trick.',
    icon: 'fa-columns',
    ageExplanation10: 'When two videos play at once, your brain can\'t think clearly about either one — that\'s the trick.',
    ageExplanation14: 'Stacked-video formats exploit limited working memory; the brain cannot evaluate or critique either stream while juggling both, so passive consumption extends.',
    detectionSignals: ['Split-screen with unrelated gameplay/captions', 'No narrative connection between top and bottom'],
    examples: ['TikTok "sludge content"', 'Reels with gameplay background', 'Shorts with subway-surfers underlay'],
  },
  {
    name: 'Rapid Topic Switching ("Brainrot")',
    category: 'Cognitive Overload',
    riskScore: 8,
    description: 'Skibidi-Toilet-style content with no narrative coherence — jumping between unrelated characters/scenarios every few seconds.',
    whyItWorks: 'Defeats narrative comprehension; trains the brain to expect novelty without resolution. Conditions the brain to tolerate progressively shorter attention spans.',
    howToSpot: 'Brainrot videos are made of random little bits — your brain feels excited but isn\'t actually learning anything.',
    icon: 'fa-brain',
    ageExplanation10: 'Brainrot videos are made of random little bits — your brain feels excited but isn\'t actually learning anything.',
    ageExplanation14: 'Rapid-switch content delivers stimulation without coherent narrative payoff; it conditions the brain to tolerate progressively shorter attention spans and rejects slower content.',
    detectionSignals: ['Topic changes >3 times per 30s', 'Absence of narrative', 'Recurring meme audio'],
    examples: ['Skibidi Toilet', 'Italian Brainrot', 'Sprunki content'],
  },
  {
    name: 'AI-Generated Content Farm',
    category: 'Cognitive Overload',
    riskScore: 10,
    description: 'Mass-produced AI-generated videos using familiar characters (Elsa, Peppa Pig, Roblox avatars) and algorithm-friendly tags to bypass moderation.',
    whyItWorks: 'Combines brand recognition with taboo curiosity, algorithm-baiting tags, and autoplay; children lack the literacy to detect canon violations.',
    howToSpot: 'Some videos that look like cartoons for kids are actually made by computers and aren\'t safe to watch.',
    icon: 'fa-robot',
    ageExplanation10: 'Some videos that look like cartoons for kids are actually made by computers and aren\'t safe to watch.',
    ageExplanation14: 'Elsagate-style content exploits the gap between automated tag-based moderation and human judgment; AI generation has lowered the cost of production so far that platforms cannot manually review the flood.',
    detectionSignals: ['Bizarre/nonsensical character combinations', 'Unnatural physics', 'Mass-uploads from a single channel (20–40 per week)', 'Gibberish or repetitive comments', 'Uncanny-valley faces'],
    examples: ['YouTube Kids "Frozen Elsa" content farms', 'Animaj-style AI animation', 'Roblox/Minecraft "Skibidi" derivatives'],
  },
  // CATEGORY 7: AUTHORITY / TRUST EXPLOITATION
  {
    name: 'Borrowed Credibility',
    category: 'Authority / Trust Exploitation',
    riskScore: 5,
    description: 'Editing in clips from CNN, BBC, or a trusted news outlet to lend authority to the creator\'s own claims, often without context.',
    whyItWorks: 'Source-amnesia effect — viewers remember the claim but not its source; the news clip "halos" the surrounding content.',
    howToSpot: 'Just because someone shows a news clip doesn\'t mean the news agrees with them.',
    icon: 'fa-newspaper',
    ageExplanation10: 'Just because someone shows a news clip doesn\'t mean the news agrees with them.',
    ageExplanation14: 'Borrowed-credibility editing exploits source amnesia; the contextual frame around the clip can completely invert what the news source actually said.',
    detectionSignals: ['News-outlet lower-third visible', 'Clip cut to 3–8 seconds', 'Immediate cut back to creator'],
    examples: ['Finance/crypto TikToks', 'Conspiracy YouTube', 'Political commentary channels'],
  },
  {
    name: 'Fake-Expert Pose',
    category: 'Authority / Trust Exploitation',
    riskScore: 7,
    description: 'Creator appears in a lab coat, stethoscope, financial-trading-floor setting, or with a wall of books, without actual credentials.',
    whyItWorks: 'Visual heuristics for expertise (Cialdini\'s Authority principle); viewers grant credibility based on costume and setting before evaluating claims.',
    howToSpot: 'A lab coat doesn\'t mean someone\'s a real doctor. Anyone can wear one.',
    icon: 'fa-user-tie',
    ageExplanation10: 'A lab coat doesn\'t mean someone\'s a real doctor. Anyone can wear one.',
    ageExplanation14: 'Costume authority exploits surface heuristics; absent verified credentials, the visual setting is doing all the persuasive work.',
    detectionSignals: ['Costume incongruent with claimed expertise', 'No on-screen credentials or licensing reference', 'Rented-set indicators (overly perfect background)'],
    examples: ['"Medical advice" TikTokers', 'Finance gurus in front of rented mansions', '"Lawyer reacts" videos'],
  },
  {
    name: 'Confidence Bias',
    category: 'Authority / Trust Exploitation',
    riskScore: 7,
    description: 'Creator delivers content with extreme certainty, no hedging, no caveats; the structural backbone of rage bait and finance-bro content.',
    whyItWorks: 'Listeners systematically over-trust confident sources. Confidence is treated as a proxy for accuracy even though research consistently shows the two are uncorrelated.',
    howToSpot: 'Just because someone sounds super sure doesn\'t mean they\'re right.',
    icon: 'fa-microphone',
    ageExplanation10: 'Just because someone sounds super sure doesn\'t mean they\'re right.',
    ageExplanation14: 'Confidence is treated by listeners as a proxy for accuracy even though research consistently shows the two are uncorrelated; the most confident creators monetize this bias.',
    detectionSignals: ['Absence of hedging language', 'No citations', 'Rapid declarative statements without pauses'],
    examples: ['"Hustle culture" TikToks', 'Conspiracy channels', 'Political commentary'],
  },
  {
    name: 'Undisclosed Sponsorship',
    category: 'Authority / Trust Exploitation',
    riskScore: 8,
    description: 'Sponsored product mention embedded in casual content without #ad / "sponsored" disclosure.',
    whyItWorks: 'Children 8–12 have difficulty recognizing embedded advertising; parasocial bonds further suppress the advertising-defense response.',
    howToSpot: 'If your favorite YouTuber mentions a product, sometimes a company is paying them to do that.',
    icon: 'fa-ad',
    ageExplanation10: 'If your favorite YouTuber mentions a product, sometimes a company is paying them to do that.',
    ageExplanation14: 'Undisclosed sponsorships exploit parasocial trust; research shows children with strong parasocial relationships rate disclosed sponsorships more positively, not less, demonstrating how parasocial loyalty overrides advertising literacy.',
    detectionSignals: ['Product featured prominently with brand visible', 'Effusive unprompted praise', 'Product link in description', 'No "#ad" disclosure'],
    examples: ['Beauty TikTok', 'Gaming-merch placements in let\'s-plays', 'Influencer "haul" videos'],
  },
  // CATEGORY 8: FOMO (FEAR OF MISSING OUT)
  {
    name: 'Trending Audio Pressure',
    category: 'FOMO',
    riskScore: 5,
    description: 'Creators rush to use whatever audio is currently algorithmically promoted; constant exposure signals that not knowing the audio = social exclusion.',
    whyItWorks: 'FoMO drives dependence on trending content for social identity; individuals with stronger media-related FoMO also demonstrate stronger media-related FoBO (fear of better options).',
    howToSpot: 'If you feel like you\'ll be left out at school for not knowing a song, that\'s the app working on you.',
    icon: 'fa-music',
    ageExplanation10: 'If you feel like you\'ll be left out at school for not knowing a song, that\'s the app working on you.',
    ageExplanation14: 'Trending-audio cascades create artificial social-identity pressure; the cost of not knowing is calibrated by schoolyard exposure, which the platform monetizes.',
    detectionSignals: ['Identical audio across dozens of unrelated videos', '"This sound" link prompting use'],
    examples: ['TikTok trends', 'Instagram Reels remixes', 'YouTube Shorts'],
  },
  {
    name: '"Watch Till the End" / Anti-Skip Hook',
    category: 'FOMO',
    riskScore: 6,
    description: 'Verbal or text instruction at the top — "Don\'t scroll, you have to see what happens at the end."',
    whyItWorks: 'Opens an explicit information-gap loop that the viewer feels obligated to close.',
    howToSpot: 'When someone says "don\'t scroll," that\'s because they\'re worried you will.',
    icon: 'fa-hourglass',
    ageExplanation10: 'When someone says "don\'t scroll," that\'s because they\'re worried you will.',
    ageExplanation14: 'Anti-skip hooks weaponize the curiosity gap explicitly; they are a soft form of forced action.',
    detectionSignals: ['"Wait for it"', '"Don\'t skip"', '"Stay till the end"', 'On-screen "the ending will shock you" text'],
    examples: ['Story-time TikToks', 'Prank reveals', '"The twist" Reels'],
  },
  {
    name: 'Exclusive-Reveal FOMO',
    category: 'FOMO',
    riskScore: 6,
    description: '"I\'ll show this only to subscribers / patrons / Discord members" — content tiered to drive paid loyalty.',
    whyItWorks: 'Scarcity + tribe-belonging + loss aversion combine to create pressure to pay or feel excluded.',
    howToSpot: 'If a YouTuber says "only my subscribers get this," they want you to pay or feel left out.',
    icon: 'fa-lock',
    ageExplanation10: 'If a YouTuber says "only my subscribers get this," they want you to pay or feel left out.',
    ageExplanation14: 'Exclusive tiers exploit loss aversion + social-identity belonging; the cost of the sub is partly to avoid feeling outside the in-group.',
    detectionSignals: ['Mention of "members-only" content', 'Previews cut off', 'Discord/Patreon promotion'],
    examples: ['YouTube channel memberships', 'Patreon "exclusive" videos', 'Twitch sub-only streams'],
  },
  {
    name: 'Autoplay / Up-Next',
    category: 'FOMO',
    riskScore: 9,
    description: 'Platform automatically plays the next recommended video without user action. 87% of users who mentioned autoplay said it undermined their sense of agency.',
    whyItWorks: 'Defeats the deliberative "should I keep watching?" moment by acting first. The EU formally classifies autoplay as a core component of "addictive design."',
    howToSpot: 'The next video starts playing on its own so you don\'t have time to decide to stop. You\'re allowed to stop.',
    icon: 'fa-play-circle',
    ageExplanation10: 'The next video starts playing on its own so you don\'t have time to decide to stop. You\'re allowed to stop.',
    ageExplanation14: 'Autoplay is the canonical attention-capture dark pattern; Lukoff et al. (CHI 2021) is the foundational peer-reviewed evidence, and the EU now formally classifies it as addictive design.',
    detectionSignals: ['Timer counting down to next video', 'No explicit play button needed', 'Default-on setting'],
    examples: ['YouTube up-next', 'Netflix episode autoplay', 'TikTok/Reels swipe-feed'],
  },
  {
    name: 'Infinite Vertical Scroll',
    category: 'FOMO',
    riskScore: 9,
    description: 'No bottom to the feed; each swipe loads more content algorithmically. Removes the natural "stopping cue."',
    whyItWorks: 'The user\'s intention to stop is gradually eroded as the feed never provides a closure signal. Without a stopping cue, the user must actively override consumption, which willpower predictably fails to do.',
    howToSpot: 'If the videos never end, your brain never gets the "okay, I\'m done" feeling. That\'s on purpose.',
    icon: 'fa-arrows-alt-v',
    ageExplanation10: 'If the videos never end, your brain never gets the "okay, I\'m done" feeling. That\'s on purpose.',
    ageExplanation14: 'Infinite scroll removes the natural endpoint that triggers behavioral satiation; without a stopping cue, the user must actively override consumption, which willpower predictably fails to do.',
    detectionSignals: ['No pagination', 'Swipe-up loads new content', 'No "you\'re all caught up" state'],
    examples: ['TikTok For You', 'Instagram Reels', 'YouTube Shorts'],
  },
];

async function main() {
  // Seed manipulation patterns from the Miro board library
  for (const pattern of patterns) {
    await prisma.pattern.upsert({
      where: { name: pattern.name },
      update: {
        category: pattern.category,
        riskScore: pattern.riskScore,
        description: pattern.description,
        whyItWorks: pattern.whyItWorks,
        howToSpot: pattern.howToSpot,
        icon: pattern.icon,
        ageExplanation10: pattern.ageExplanation10,
        ageExplanation14: pattern.ageExplanation14,
        detectionSignals: pattern.detectionSignals,
        examples: pattern.examples,
      },
      create: pattern,
    });
  }

  // Create demo parent account
  const parentHash = await bcrypt.hash('parent123', 10);
  const parent = await prisma.user.upsert({
    where: { email: 'parent@clearfeed.dev' },
    update: {},
    create: {
      email: 'parent@clearfeed.dev',
      name: 'Alex Chen',
      passwordHash: parentHash,
      role: 'PARENT',
    },
  });

  // Create demo child account
  const childHash = await bcrypt.hash('child123', 10);
  const child = await prisma.user.upsert({
    where: { email: 'maya@clearfeed.dev' },
    update: {},
    create: {
      email: 'maya@clearfeed.dev',
      name: 'Maya Chen',
      passwordHash: childHash,
      role: 'CHILD',
      parentId: parent.id,
    },
  });

  // Create child profile
  await prisma.childProfile.upsert({
    where: { userId: child.id },
    update: {},
    create: {
      userId: child.id,
      age: 10,
      contentThreshold: 5,
    },
  });

  console.log('Seed complete: 49 patterns (8 categories), parent, and child accounts created.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
